### ISSUE TITLE
Default Admin Credentials Don't Work

### ISSUE THREAD

**Issue by YMan84** [unmonoqueteclea/voilib#2]
Thank you for making the service super easy to setup/start with the docker compose instructions, 
I'm not able to login with the default admin credentials though. I get a `Invalid credentials. Please, try again` error.

I copied and pasted the login credentials directly from the Github readme, and i also tried typing them out, with the same result.
I also tried it without the *'s in case it was a markdown formatting bug, but same result as well.

```
By default user voilib-admin with password *audio*search*engine* will be created.
```

![image](https://github.com/unmonoqueteclea/voilib/assets/62976572/003df81d-795f-4cc9-8151-9b5ada9591ab)

**Comment by unmonoqueteclea** [comment]
Ups sorry, I have a typo in the docs. It's: `*audio*search*engine`

**Comment by unmonoqueteclea** [comment]
Fixed in the docs, thank you very much for telling me.
